application: sql-shell
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  expiration: 1d

- url: /
  static_files: static/shell.html
  upload: static/shell.html

- url: /shell.do
  script: shell.py
