application: imageconvertdemo-test
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: image_flipper.py
  login: admin

- url: /imagestatus
  script: image_flipper.py
  login: admin

- url: /images
  script: image_flipper.py

- url: /taskdata
  script: image_flipper.py
