application: your-gae-app-id
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: handle_mail.py
  login: admin

- url: /upload/
  script: upload.py

- url: /
  script: main.py

builtins:
- datastore_admin: on
- remote_api: on

inbound_services:
- mail
